/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 9c73f6fd1b8e102627d3a324288ce615)
interface __BaseEnv_Env {
	DB: D1Database;
	GUEST_LIMITER: RateLimit;
	PLAY_LIMITER: RateLimit;
	ACCOUNT_LIMITER: RateLimit;
	LOCATION_HINT: string;
	ALLOWED_ORIGINS: string;
	TEST_HOOKS: string;
	AUTH_SECRET: string;
	MATCH: DurableObjectNamespace<import("./src/index").MatchRoom>;
	LOBBY: DurableObjectNamespace<import("./src/index").Lobby>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MatchRoom" | "Lobby";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LOCATION_HINT" | "ALLOWED_ORIGINS" | "TEST_HOOKS" | "AUTH_SECRET">> {}
}
